spring:
  datasource:
    druid:
      url: jdbc:mysql://db4free.net:3306/testspringboot?serverTimezone=Asia/Shanghai&useUnicode=true&characterEncoding=utf8
      username: testspringboot
      password: rencw1225